<a href="https://colab.research.google.com/github/Mahtab14H/BDDA-all/blob/main/iim_calcutta_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# 1.0.1
from sklearn.model_selection import train_test_split
from sklearn.ensemble import  RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline

# 1.0.2
from pathlib import Path
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# For skopt routines
! pip install scikit-optimize
# 0.1 For plotting skopt results
! pip install 'scikit-optimize[plots]'

Collecting scikit-optimize
  Downloading scikit_optimize-0.9.0-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.3.2)
Collecting pyaml>=16.9 (from scikit-optimize)
  Downloading pyaml-23.12.0-py3-none-any.whl (23 kB)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.25.2)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.11.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.2.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->scikit-optimize) (3.3.0)
Installing collected packages: pyaml, scikit-optimize
Successfully installed pyaml-23.12.0 scikit-optimize-0.9.0
Requirement already satisfied: scikit-optimize[plots] in /usr/local/lib/python3.10/dist-packages (0.9.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (1.3.2)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (23.12.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (1.25.2)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (1.11.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (1.2.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize[plots]) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-optimize[plots]) (2.8.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize[plots]) (6.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->scikit-optimize[plots]) (3.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=2.0.0->scikit-optimize[plots]) (1.16.0)

In [ ]:
#1.0 Clear ipython memory
#%reset -f

# 1.1 Data manipulation and plotting modules
import numpy as np
import pandas as pd


# 1.2 Data pre-processing
#     z = (x-mean)/stdev
from sklearn.preprocessing import StandardScaler as ss

# 1.3 Dimensionality reduction and noise removal
from sklearn.decomposition import PCA

# 1.4 Data splitting and model parameter search
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

# 1.5 Model pipelining
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

# 1.6 Hyperparameter optimization
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

In [ ]:
#1.9 Model evaluation metrics
from sklearn.metrics import accuracy_score, f1_score
#from sklearn.metrics import plot_roc_curve
from sklearn.metrics import confusion_matrix

# 1.10
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import plot_importance

# 1.11 Permutation feature importance
from sklearn.inspection import permutation_importance

In [ ]:
#1.13 Used in Randomized parameter search
from scipy.stats import uniform
# 1.12 Misc
import time
import os
import gc
import random
# 1.13 Used in Randomized parameter search
from scipy.stats import uniform
from matplotlib.ticker import EngFormatter
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import statsmodels as sm
import scipy.stats as sps
import statsmodels.formula.api as smf
import numpy as np

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/Mahtab14H/BDDA-all/main/Bank_Marketing_iim_calcutta.csv")

In [ ]:
data

,customer_age,customer_job,marital_status,hghest_education,credit_default,account_balance,housing,loan,contact_mode,call_day,call_month,call_duration,campaign_count,previous_campaign,previous_campaign_count,previous_campaign_outcome,deposites_purchased
0,34,blue-collar,divorced,secondary,no,-294,yes,no,unknown,12,may,163,2,-1,0,unknown,no
1,34,technician,married,secondary,no,222,yes,no,unknown,12,may,149,6,-1,0,unknown,no
2,35,technician,married,unknown,no,86,yes,no,unknown,12,may,33,4,-1,0,unknown,no
3,57,management,divorced,secondary,no,0,yes,yes,unknown,12,may,144,6,-1,0,unknown,no
4,28,blue-collar,married,primary,no,26,no,no,unknown,12,may,40,3,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43093,47,management,married,tertiary,no,0,no,no,cellular,27,oct,508,1,-1,0,unknown,yes
43094,61,retired,married,secondary,no,1058,no,no,cellular,27,oct,277,1,92,5,success,no
43095,24,student,single,secondary,no,822,no,no,cellular,27,oct,184,1,91,2,failure,yes
43096,70,retired,married,secondary,no,0,no,no,cellular,27,oct,258,1,92,5,success,yes
43097,53,blue-collar,married,primary,no,1294,no,no,unknown,28,oct,71,1,-1,0,unknown,no

In [ ]:
data.isnull().sum()
# There are no null values in data . hence , no need to impute it

customer_age                 0
customer_job                 0
marital_status               0
hghest_education             0
credit_default               0
account_balance              0
housing                      0
loan                         0
contact_mode                 0
call_day                     0
call_month                   0
call_duration                0
campaign_count               0
previous_campaign            0
previous_campaign_count      0
previous_campaign_outcome    0
deposites_purchased          0
dtype: int64

In [ ]:
data.describe()

,customer_age,account_balance,call_day,call_duration,campaign_count,previous_campaign,previous_campaign_count
count,43098.000000,43098.000000,43098.000000,43098.000000,43098.000000,43098.000000,43098.000000
mean,40.950021,1400.466750,16.225208,257.840596,2.806279,41.983062,0.602371
std,10.671794,3081.352007,8.291505,257.886291,3.156180,101.836452,2.347143
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,76.000000,9.000000,102.000000,1.000000,-1.000000,0.000000
50%,39.000000,473.000000,17.000000,179.000000,2.000000,-1.000000,0.000000
75%,48.000000,1489.000000,22.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,854.000000,275.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43098 entries, 0 to 43097
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_age               43098 non-null  int64
 1   customer_job               43098 non-null  object
 2   marital_status             43098 non-null  object
 3   hghest_education           43098 non-null  object
 4   credit_default             43098 non-null  object
 5   account_balance            43098 non-null  int64
 6   housing                    43098 non-null  object
 7   loan                       43098 non-null  object
 8   contact_mode               43098 non-null  object
 9   call_day                   43098 non-null  int64
 10  call_month                 43098 non-null  object
 11  call_duration              43098 non-null  int64
 12  campaign_count             43098 non-null  int64
 13  previous_campaign          43098 non-null  int64
 14  previous_campaign_count    43098 non-null  int64
 15  previous_campaign_outcome  43098 non-null  object
 16  deposites_purchased        43098 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.6+ MB

In [15]:
data.shape
data['customer_job'].value_counts()

(43098, 17)

management       9157
blue-collar      9039
technician       7297
admin.           4905
services         3901
retired          2190
self-employed    1528
entrepreneur     1426
unemployed       1252
housemaid        1218
student           905
unknown           280
Name: customer_job, dtype: int64

In [16]:
data['hghest_education'].value_counts()

secondary    22045
tertiary     12887
primary       6443
unknown       1723
Name: hghest_education, dtype: int64

In [ ]:
# here , student and unknown makes a small chunk

In [17]:
data['contact_mode'].value_counts()

cellular     29217
unknown      10981
telephone     2900
Name: contact_mode, dtype: int64

In [ ]:
# Here , major contact mode is of cellular type and least is of telephone type

In [19]:
data['marital_status'].value_counts()

married     25939
single      12232
divorced     4927
Name: marital_status, dtype: int64

In [ ]:
Pie_chart= px.pie(data, title='credit default ', values='Units Sold',  color_discrete_sequence=["#0083B8"], names='Product')
Pie_chart.show()